version: "3.5"

services:
  # https://hub.docker.com/_/nginx/
  nginx:
    image: nginx:1.13-alpine
    ports:
      - "80:80"

  # https://hub.docker.com/r/miveo/centos-php-fpm/
  php:
    container_name: ${COMPOSE_PROJECT_NAME}_php
    image: ${COMPOSE_PROJECT_NAME}_php:${PHP_VERSION}-${DEBIAN_VERSION}
    build:
      context: ${PATH_HOST}/php
      args:
        PHP_VERSION: ${PHP_VERSION}
        DEBIAN_VERSION: ${DEBIAN_VERSION}
        INSTALL_XDEBUG: ${INSTALL_XDEBUG}
        INSTALL_OPCACHE: ${INSTALL_OPCACHE}
        INSTALL_COMPOSER: ${INSTALL_COMPOSER}

    ### MySQL Container ###
  mysql:
    container_name: test_mysql
    image: mysql:${MYSQL_VERSION}
    command: --sql_mode="" --collation-server=utf8mb4_unicode_ci --character-set-server=utf8mb4
    ports:
      - 3306:3306
    volumes:
      - ${PATH_HOST}/mysql/datas:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root

  # https://hub.docker.com/r/kkarczmarczyk/node-yarn/
  yarn:
    image: kkarczmarczyk/node-yarn:8.0-slim
    command: bash -c "yarn install && yarn build"
  # https://hub.docker.com/_/postgres/
  # db:
  #   image: postgres:9.6-alpine
  #   environment:
  #     - POSTGRES_USER=${DATABASE_USER}
  #     - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
  #     - POSTGRES_DB=${DATABASE_NAME}
  #     - POSTGRES_PORT=${DATABASE_PORT}
  #   ports:
  #     - "5432:5432"
