version: "3.5"

services:
  # https://hub.docker.com/_/nginx/
  nginx:
    image: nginx:1.13-alpine
    volumes:
      - ./nginx/nginx-dev.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"

  # https://hub.docker.com/r/miveo/centos-php-fpm/
  php:
    container_name: ${COMPOSE_PROJECT_NAME}_php
    image: ${COMPOSE_PROJECT_NAME}_php:${PHP_VERSION}-${DEBIAN_VERSION}
    build:
      context: ${PATH_HOST}/php
      args:
        PHP_VERSION: ${PHP_VERSION}
        DEBIAN_VERSION: ${DEBIAN_VERSION}
        INSTALL_XDEBUG: ${INSTALL_XDEBUG}
        INSTALL_OPCACHE: ${INSTALL_OPCACHE}
        INSTALL_COMPOSER: ${INSTALL_COMPOSER}

    ### MySQL Container ###
  mysql:
    container_name: ${COMPOSE_PROJECT_NAME}_mysql
    image: mysql:${MYSQL_VERSION}
    command: --sql_mode="" --collation-server=utf8mb4_unicode_ci --character-set-server=utf8mb4
    ports:
      - 3306:3306
    volumes:
      - ${PATH_HOST}/mysql/datas:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root

    ### Node Container ###
  ### Node Container ###
  node:
    container_name: ${COMPOSE_PROJECT_NAME}_node
    build:
      context: ${PATH_HOST}/node
    volumes:
      - ../node:/app
    ports:
      - "3000:3000"
    # command: sh -c 'npm install && npm start && exit && echo "ok"'
