version: "3.5"

services:
  nginx:
    volumes:
      - source_sync:/var/www/app:nocopy
  php:
    working_dir: /var/www/app/
    env_file: .env
    volumes:
      - source_sync:/var/www/app:nocopy
      - ./php/php.ini:/usr/local/etc/php/php.ini

volumes:
  # Handle by docker-sync
  source_sync:
    name: ${COMPOSE_PROJECT_NAME}_sync # docker-sync do not use the compose project name by default, so we do.
    external: true
